### ISSUE TITLE
What is the admin password? (aka "How reset admin password?")

### ISSUE THREAD

**Issue by bittner** [shlomizadok/foreman-docker-compose#9]
I can successfully bring up the Docker Compose setup (simply running `docker-compose up`), then The Foreman shows up successfully on http://localhost after some time. However, I don't see any hint on the (default) password of the `admin` user anywhere (and it's not `changeme` anymore, as it used to be [a few versions ago](https://theforeman.org/manuals/1.1/index.html#Installation)).

According to [current installation instructions](https://theforeman.org/manuals/1.17/index.html#3.4InstallFromSource) the admin password is printed out during the installation. Unfortunately, this helps little when you forget to record that information. Is there an easy way to (re)set a user's password?

Note that there seems to be no `foreman-rake` command in any of the built images to run [commands to reset the password](http://erwan.com/en/2014/10/06/foreman-lost-reset-password/).

If there is a solution for this it may be a good idea to document this in the README.

**Comment by bittner** [comment]
I found the `foreman-rake` script in the `foreman` container, but it [assumes to be installed alongside a user](https://github.com/theforeman/foreman/blob/develop/script/foreman-rake#L10) called `foreman`, which is not present on the system:

```bash
$ docker-compose run --rm foreman bash
Starting foremandockercompose_memcache_1 ... done
Starting foremandockercompose_db_1 ... done
Starting foremandockercompose_proxy_1 ... done
```
```bash
[root@686c1433e0e1 app]# find / -name foreman-rake
/usr/src/app/script/foreman-rake
```
```bash
[root@686c1433e0e1 app]# /usr/src/app/script/foreman-rake permissions:reset
/usr/src/app/script/foreman-rake: line 10: cd: ~foreman: No such file or directory
Cannot change to foreman home directory
```
Is that something we need to fix, or is there a different container I should use?

**Comment by bittner** [comment]
It looks like we should clone the application source code into `/home/foreman` (creating the user beforehand). I've not tried that out yet, but I get errors when I let the `foreman-rake` script [`cd` into `/usr/src/app/`](https://github.com/theforeman/foreman/blob/develop/script/foreman-rake#L10) instead:

```bash
[root@686c1433e0e1 app]# /usr/src/app/script/foreman-rake permissions:reset
Log file /usr/src/app/log/production.log cannot be opened. Falling back to STDOUT
 WARN  root : No appender set, logging to STDOUT
 INFO  app : memcached cache backend enabled: [:dalli_store, "memcache", {:namespace=>"foreman", :expires_in=>86400, :compress=>true}]
Apipie cache enabled but not present yet. Run apipie:cache rake task to speed up API calls.
 WARN  app : Creating scope :completer_scope. Overwriting existing method Location.completer_scope.
 WARN  app : Creating scope :completer_scope. Overwriting existing method Organization.completer_scope.
 INFO  audit : update event for Setting with id 2
 INFO  audit : update event for Setting with id 3
 INFO  audit : update event for Setting with id 24
 INFO  audit : update event for Setting with id 26
 INFO  audit : update event for Setting with id 64
 INFO  audit : update event for Setting with id 80
rake aborted!
Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/src/app/tmp
/usr/src/app/config/initializers/secret_token.rb:6:in `mkdir'
/usr/src/app/config/initializers/secret_token.rb:6:in `<top (required)>'
/usr/share/gems/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `load'
/usr/share/gems/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `block in load'
/usr/share/gems/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/share/gems/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `load'
/usr/share/gems/gems/railties-5.1.6/lib/rails/engine.rb:655:in `block in load_config_initializer'
/usr/share/gems/gems/activesupport-5.1.6/lib/active_support/notifications.rb:168:in `instrument'
/usr/share/gems/gems/railties-5.1.6/lib/rails/engine.rb:654:in `load_config_initializer'
/usr/share/gems/gems/railties-5.1.6/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/usr/share/gems/gems/railties-5.1.6/lib/rails/engine.rb:611:in `each'
/usr/share/gems/gems/railties-5.1.6/lib/rails/engine.rb:611:in `block in <class:Engine>'
/usr/share/gems/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `instance_exec'
/usr/share/gems/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `run'
/usr/share/gems/gems/railties-5.1.6/lib/rails/initializable.rb:59:in `block in run_initializers'
/usr/share/gems/gems/railties-5.1.6/lib/rails/initializable.rb:48:in `each'
/usr/share/gems/gems/railties-5.1.6/lib/rails/initializable.rb:48:in `tsort_each_child'
/usr/share/gems/gems/railties-5.1.6/lib/rails/initializable.rb:58:in `run_initializers'
/usr/share/gems/gems/railties-5.1.6/lib/rails/application.rb:353:in `initialize!'
/usr/share/gems/gems/railties-5.1.6/lib/rails/railtie.rb:185:in `public_send'
/usr/share/gems/gems/railties-5.1.6/lib/rails/railtie.rb:185:in `method_missing'
/usr/src/app/config/environment.rb:5:in `<top (required)>'
/usr/share/gems/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/usr/share/gems/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/usr/share/gems/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/share/gems/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/usr/share/gems/gems/railties-5.1.6/lib/rails/application.rb:329:in `require_environment!'
/usr/share/gems/gems/railties-5.1.6/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/usr/share/gems/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/usr/share/gems/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/usr/share/gems/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
Tasks: TOP => permissions:reset => environment
(See full trace by running task with --trace)
```

**Comment by bittner** [comment]
@shlomizadok Could you share which pieces of the The Foreman source code you use to create all the Dockerfiles? I'm having issues getting a running setup when I introduce a `foreman` user in all Dockerfiles ([see changes](https://github.com/shlomizadok/foreman-docker-compose/compare/master...painless-software:feature/foreman-user-insteadof-root?expand=1)).

I believe, a sustainable solution must match the original setup, ideally completely. I'd like to make sure this (setup or knowledge about its details) can easily be derived. Not sure if I can find this easily somewhere in the [foreman-installer](https://github.com/theforeman/foreman-installer).

**Comment by bittner** [comment]
Yay, I managed to run `rake permissions:reset` following the idea of the `foreman-init` service:

```bash
$ docker-compose run --rm foreman-init bundle exec rake permissions:reset
Starting foremandockercompose_db_1 ... done
Apipie cache enabled but not present yet. Run apipie:cache rake task to speed up API calls.
Reset to user: admin, password: v6YbJxR6SKhocxyT
```

Anyway, I still think it's a good idea to align the behavior of this setup with the one created by the `foreman-installer`. I've [opened a thread](https://community.theforeman.org/t/docker-compose-setup-compatible-with-foreman-installer/10127) for this in the Foreman Community Forum.

**Comment by shlomizadok** [comment]
Hey, I am not actively maintaining this repo. Would love if it would move to @theforeman repo.
I am really happy that you managed to solved the issue though 👍

**Comment by bittner** [comment]
> Would love if it would move to @theforeman repo.

This will probably not happen. You've seen the discussions.
